#!/usr/bin/env node
// Generates the typed contract modules (src/abi/*.ts) from the Foundry artifacts in contracts/out:
//   DripPool.ts  the singleton itself (ABI + creation bytecode + CREATE2 salt label)
//   MockUSDC.ts  the FiatToken-like test mock (6 decimals, blocklist), used by the SDK's anvil tests only
// src/abi/ holds generated files only (biome skips it).
//
//   pnpm contracts:abi                          # forge build + write src/abi/DripPool.ts
//   pnpm --filter @arcdrip/sdk generate:abi     # write it from the current artifact (run `forge build` first)
//   pnpm --filter @arcdrip/sdk check:abi        # exit 1 if the committed module does not match the artifact
//
// --check is strict as soon as either side exists: it fails on a mismatch, on an artifact without a committed
// module, and on a committed module without an artifact. Only when neither exists (before DripPool.sol is written)
// does it print a notice and exit 0.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sdkDir = resolve(here, '..');
const repoDir = resolve(sdkDir, '../..');
const check = process.argv.includes('--check');
const show = (path) => relative(repoDir, path);
const header =
  '// AUTO-GENERATED by packages/sdk/scripts/generate-abi.mjs from contracts/out. Do not edit.\n' +
  '// Regenerate: pnpm contracts:abi\n\n';

/** One generated module per contract: where the artifact is, where the module goes, what the module says. */
const modules = [
  {
    artifact: resolve(repoDir, 'contracts/out/DripPool.sol/DripPool.json'),
    module: resolve(sdkDir, 'src/abi/DripPool.ts'),
    render: (a) =>
      header +
      `export const dripPoolAbi = ${JSON.stringify(a.abi, null, 2)} as const;\n\n` +
      '/** Creation bytecode (constructor: usdc). Local anvil tests and CREATE2 checks. */\n' +
      `export const dripPoolBytecode = '${a.bytecode.object}' as const;\n\n` +
      '/** CREATE2 salt label used by contracts/script/Deploy.s.sol: salt = keccak256("arcdrip.v1"). */\n' +
      "export const DRIP_POOL_CREATE2_SALT = 'arcdrip.v1' as const;\n",
  },
  {
    artifact: resolve(repoDir, 'contracts/out/MockUSDC.sol/MockUSDC.json'),
    module: resolve(sdkDir, 'src/abi/MockUSDC.ts'),
    render: (a) =>
      header +
      '/** Test-only FiatToken-like mock: 6 decimals, blocklist, a transfer that can return false.\n' +
      ' *  Deployed by the SDK anvil tests. Never use it on a real network. */\n' +
      `export const mockUsdcAbi = ${JSON.stringify(a.abi, null, 2)} as const;\n\n` +
      `export const mockUsdcBytecode = '${a.bytecode.object}' as const;\n`,
  },
];

let stale = false;
for (const { artifact: artifactPath, module: modulePath, render } of modules) {
  const hasArtifact = existsSync(artifactPath);
  const hasModule = existsSync(modulePath);
  if (!hasArtifact && !hasModule) {
    console.log(`not built yet (no ${show(artifactPath)}, no ${show(modulePath)}): nothing to do`);
    continue;
  }
  if (!hasArtifact) {
    console.error(
      `missing ${show(artifactPath)} while ${show(modulePath)} exists; run \`forge build\` in contracts/`,
    );
    process.exit(1);
  }
  const content = render(JSON.parse(readFileSync(artifactPath, 'utf8')));
  const current = hasModule ? readFileSync(modulePath, 'utf8') : null;
  if (current === content) {
    console.log(`${show(modulePath)} is up to date`);
    continue;
  }
  if (check) {
    console.error(
      `${show(modulePath)} ${current === null ? 'is missing' : 'is stale'} for ${show(artifactPath)}; ` +
        'run `pnpm contracts:abi`',
    );
    stale = true;
    continue;
  }
  mkdirSync(dirname(modulePath), { recursive: true });
  writeFileSync(modulePath, content);
  console.log(`wrote ${show(modulePath)}`);
}
process.exit(stale ? 1 : 0);
